// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	models "github.com/joaofilippe/americanas-desafio/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// IListNodeService is an autogenerated mock type for the IListNodeService type
type IListNodeService struct {
	mock.Mock
}

// MergeListNode provides a mock function with given fields: id
func (_m *IListNodeService) GetMergedListNode(id int64) (*models.ListNode, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MergeListNode")
	}

	var r0 *models.ListNode
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.ListNode, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.ListNode); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListNode)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveListsNode provides a mock function with given fields: list1, list2
func (_m *IListNodeService) SaveListsNode(list1 *models.ListNode, list2 *models.ListNode) (int64, error) {
	ret := _m.Called(list1, list2)

	if len(ret) == 0 {
		panic("no return value specified for SaveListsNode")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.ListNode, *models.ListNode) (int64, error)); ok {
		return rf(list1, list2)
	}
	if rf, ok := ret.Get(0).(func(*models.ListNode, *models.ListNode) int64); ok {
		r0 = rf(list1, list2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*models.ListNode, *models.ListNode) error); ok {
		r1 = rf(list1, list2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIListNodeService creates a new instance of IListNodeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIListNodeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IListNodeService {
	mock := &IListNodeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
