apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-node
spec:
  selector:
    matchLabels:
      app: list-node
  template:
    metadata:
      labels:
        app: list-node
    spec:
      containers:
      - name: list-node
        image: joaofilippe/list-node:0.2.0

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: list-node-env
        - secretRef:
            name: list-node-secret